### ISSUE TITLE
Code-snippet is not a helper on newest ember 😂

### ISSUE THREAD

**Issue by jayzhou3** [ef4/ember-code-snippet#66]
ember-cli-build.js
```
 let app = new EmberAddon(defaults, {
        // Add options here
        snippetSearchPaths: ["tests/dummy/app"]
    });
```

package.json
```
"ember-code-snippet": "^3.0.0",
```

I had a ember version '3.10.1' 

on my random template: 

{{code-snippet name="fun.hbs"}} 

I get the error on the dummy app: code-snippet is not a helper on newest ember

**Comment by simonihmig** [comment]
`{{code-snippet}}` indeed is not a thing anymore, after substantial changes have been introduced in v3 of this addon (not related to the Ember version). See https://github.com/ef4/ember-code-snippet#helper-usage for up to date documentation!

There is a leftover of `{{code-snippet}}` in the Readme, which we need to fix though!

**Comment by simonihmig** [comment]
#67 is the fix for the Readme glitch. Also have a look at the [Changelog](https://github.com/ef4/ember-code-snippet/blob/master/CHANGELOG.md#300) for v3, which describes this breaking change! Sorry if that change was not obvious, but as I think there is no problem otherwise here, I will close this now...
